In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1,2,3],[4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7,8,9],[10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [5]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [6]:
tensor2.requires_grad

False

In [7]:
tensor1.requires_grad

True

In [8]:
output_tensor = (tensor1 * tensor2)

In [9]:
output_tensor.grad_fn

In [10]:
output_tensor = (tensor1 * tensor2).mean()

In [11]:
output_tensor.grad_fn