In [1]:
import torch

print(torch.__version__)

1.4.0


In [3]:
torch.get_default_dtype()

torch.float32

In [5]:
torch.set_default_dtype(torch.float64)

In [6]:
torch.get_default_dtype()

torch.float64

In [7]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
torch.is_tensor(tensor_arr)

True

In [16]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.5980, 0.5549, 0.2218],
        [0.0923, 0.2610, 0.7373]])

In [25]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [26]:
new_tensor = initial_tensor.add(5)

In [27]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [28]:
initial_tensor


tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [29]:
initial_tensor.add_(8)

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [30]:
new_tensor = initial_tensor.sqrt_()

In [31]:
new_tensor

tensor([[4.2426, 4.2426, 4.2426],
        [4.2426, 4.2426, 4.2426]])

In [32]:
x = torch.linspace(start = 0.1, end = 10.0, steps = 15)

In [33]:
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [34]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [41]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

new_tensor = torch.cat((tensor1, tensor2, tensor3), 0)
new_tensor

TypeError: 'tuple' object is not callable

In [44]:
random_tensor = torch.Tensor([[10,8,30],[40,5,6],[12,2,100]])

In [45]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [46]:
sorted_tensor, sorted_inidces = torch.sort(random_tensor)

In [47]:
sorted_tensor


tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [48]:
sorted_inidces

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])